// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.Domen;

#nullable disable

namespace WebApplication2.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20221004095811__initial")]
    partial class _initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication2.Models.EmployeeInfo", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            ID = new Guid("9e468402-2999-422b-8056-3a5002357a80"),
                            Company = "Company 1",
                            Department = "Dep 1",
                            Gender = "Man",
                            Name = "name 1"
                        },
                        new
                        {
                            ID = new Guid("9bbc96b5-3dda-4297-8d08-b5348646098b"),
                            Company = "Company 2",
                            Department = "Dep 1",
                            Gender = "Man",
                            Name = "name 2"
                        },
                        new
                        {
                            ID = new Guid("bd58569e-3659-49e8-bc42-711f51c077d2"),
                            Company = "Company 2",
                            Department = "Dep 1",
                            Gender = "Woman",
                            Name = "name 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
