// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.Domen;

#nullable disable

namespace WebApplication2.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20221003110839__initial")]
    partial class _initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication2.Models.EmployeeInfo", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Test");

                    b.HasData(
                        new
                        {
                            ID = new Guid("a37e2f12-3d37-4102-a791-ca2b55f09193"),
                            Company = "Company 1",
                            Department = "Dep 1",
                            Gender = "Man",
                            Name = "name 1"
                        },
                        new
                        {
                            ID = new Guid("e330c4db-03cd-49cb-8552-fe2598afdadb"),
                            Company = "Company 2",
                            Department = "Dep 1",
                            Gender = "Man",
                            Name = "name 2"
                        },
                        new
                        {
                            ID = new Guid("113def3b-08d8-48c2-86b5-90180cb95949"),
                            Company = "Company 2",
                            Department = "Dep 1",
                            Gender = "Woman",
                            Name = "name 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
